### ISSUE TITLE
How to estimate uncertainty at each level of the immune cell type hierarchy?

### ISSUE THREAD

**Issue by maximz** [hammerlab/immune-infiltrate-explorations#43]

**Comment by jburos** [comment]
This issue was based on a comment in our abstract, which read:

> Our method produces significantly more accurate estimates of immune infiltration overall and by cell type, with robust estimates of uncertainty at each level of the immune cell type hierarchy.

Just to be clear, we are estimating the uncertainty at each cell type now - this is the range of % composition estimates in the posterior predicted (`OOS`) distribution.  We can do this per cell type, at each level of the hierarchy. What we are not doing is estimating the immune infiltrate proportion _overall_. IE what portion of the sample is comprised of immune cells, and which is something else (tumor, stromal, etc)?

**Comment by maximz** [comment]
Makes sense, thanks @jburos . Sounds like this should be merged into #39 , yes?

**Comment by jburos** [comment]
Yep - agreed.
